# Generated by Django 4.1.6 on 2023-06-26 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='series',
            name='CACA',
        ),
    ]
