# Generated by Django 4.1.6 on 2023-06-26 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0002_remove_series_caca'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='finished_year_only',
        ),
        migrations.RemoveField(
            model_name='film',
            name='finished_year_only',
        ),
        migrations.RemoveField(
            model_name='videogame',
            name='finished_year_only',
        ),
    ]
