# Generated by Django 4.1.6 on 2023-06-26 22:12

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0003_remove_book_finished_year_only_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='final_date',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10, null=True), null=True, size=None),
        ),
    ]
