# Generated by Django 4.1.6 on 2023-06-26 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0004_book_final_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='finished_date',
        ),
    ]
