# Generated by Django 4.1.6 on 2023-06-26 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0005_remove_book_finished_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='final_date',
            new_name='finished_date',
        ),
    ]
