# Generated by Django 4.1.6 on 2023-06-26 22:18

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0006_rename_final_date_book_finished_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='final_date',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10, null=True), null=True, size=None),
        ),
    ]
