# Generated by Django 4.1.6 on 2023-06-26 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0007_film_final_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='finished_date',
        ),
    ]
