# Generated by Django 4.1.6 on 2023-06-26 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0010_videogame_final_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videogame',
            name='finished_date',
        ),
    ]
