# Generated by Django 4.1.6 on 2023-06-26 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0011_remove_videogame_finished_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='videogame',
            old_name='final_date',
            new_name='finished_date',
        ),
    ]
