# Generated by Django 4.1.6 on 2023-06-27 09:17

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0012_rename_final_date_videogame_finished_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cosa',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=40, null=True), null=True, size=None),
        ),
        migrations.AddField(
            model_name='videogame',
            name='cosa',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=40, null=True), null=True, size=None),
        ),
    ]
