# Generated by Django 4.1.6 on 2023-06-27 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0013_book_cosa_videogame_cosa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='finished_date',
        ),
    ]
