# Generated by Django 4.1.6 on 2023-06-27 10:25

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0016_remove_book_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cosa',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10, null=True), null=True, size=None),
        ),
    ]
