# Generated by Django 4.1.6 on 2023-06-27 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0018_rename_finished_date_book_language'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='cosa',
            new_name='finished_date',
        ),
    ]
