# Generated by Django 4.1.6 on 2023-06-27 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0019_rename_cosa_book_finished_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='videogame',
            old_name='platform',
            new_name='platform_todelete',
        ),
    ]
