# Generated by Django 4.1.6 on 2023-06-27 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0020_rename_platform_videogame_platform_todelete'),
    ]

    operations = [
        migrations.RenameField(
            model_name='videogame',
            old_name='cosa',
            new_name='platform',
        ),
    ]
