# Generated by Django 4.1.6 on 2023-06-27 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0021_rename_cosa_videogame_platform'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videogame',
            name='platform_todelete',
        ),
    ]
